apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s-pod
  namespace: hello-kubernetes
  labels:
    app: hello-k8s
spec:
  containers:
    - name: hello-k8s-container
      image: abhilekkala/hello-k8s-app:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 5000