apiVersion: v1
kind: Service
metadata:
  name: hello-k8s-service
  namespace: hello-kubernetes
spec:
  type: NodePort
  selector:
    app: hello-k8s
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007